### ISSUE TITLE
Trouble compiling, can't pass tests

### ISSUE THREAD

**Issue by davidreedernst** [Imagick/imagick#563] opened 2022-09-08 13:25 UTC
I'm sure this is not a problem with the imagick code per se, but I'm trying to compile imagick from source and it's not working. My basic story is as follows: we're running on a fresh Ubuntu 20.4 system. We want to run imagemagick 7.x, which isn't available as a normal Ubuntu package.  I downloaded the ImageMagick-7.1.0-47 source code and compiled that, it appears to be working. Then did git clone https://github.com/Imagick/imagick, phpize, configure, make. I had to edit the Makefile to 

add `-I/usr/local/include/ImageMagick-7` to `INCLUDES` (otherwise `fatal error: MagickWand/MagickWand.h: No such file or directory`)
add `-DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16` to `CPPFLAGS` (otherwise lots of warnings)

with those changes, I can run make without errors or warnings.  However, when I run `make test` all of the tests fail.  I tried manually running `tests/001_imagick_readimage.sh` and got this fatal error:

`/usr/bin/php8.1: symbol lookup error: /root/imagick/modules/imagick.so: undefined symbol: MagickWandGenesis`

fwiw, I have `extension=imagick.so` in my system php.ini file, but I seem to get the same results whether it's there or not.  Not surprisingly `php -m` does not report imagick in any case.

Again, I know is usually a place for people who are actually troubleshooting the imagick code, so I'm sorry to intrude with such a user-level question. But I don't know where else to turn, since the problem does seem specific to the imagick source distribution.  Can you help me?

**Comment by Danack** [comment] 2022-09-08 13:31
> I had to edit the Makefile to

That's a not a good idea.

Please can you say the original error you get from compiling after doing `phpize`, `configure`, `make install`.

> is usually a place for people who are actually troubleshooting the imagick code,

**Comment by davidreedernst** [comment] 2022-09-08 14:44
Yeah, I didn't feel good about editing the makefile, either. But I couldn't find another way to get that path included. I tried setting environment variables (PATH, LD_LIBRARY_PATH) before running make (and before configure), they never showed up in the `-I` flags in the output from `make`.  Advice on the proper way to do that would be greatly appreciated.  Similarly with the `MAGICKCORE` variables.

If I just follow the instructions as they are in the README.md file, I get no errors from `phpize` or `configure`, but `make` exits with an error almost immediately. Here's the complete output:

`/bin/bash /home/myuser/unzip/imagick/libtool --mode=compile cc -I. -I/home/myuser/unzip/imagick -I/home/myuser/unzip/imagick/include -I/home/myuser/unzip/imagick/main -I/home/myuser/unzip/imagick -I/usr/include/php/20210902 -I/usr/include/php/20210902/main -I/usr/include/php/20210902/TSRM -I/usr/include/php/20210902/Zend -I/usr/include/php/20210902/ext -I/usr/include/php/20210902/ext/date/lib  -DHAVE_CONFIG_H  -g -O2    -DZEND_COMPILE_DL_EXT=1 -c /home/myuser/unzip/imagick/imagick_file.c -o imagick_file.lo  -MMD -MF imagick_file.dep -MT imagick_file.lo
libtool: compile:  cc -I. -I/home/myuser/unzip/imagick -I/home/myuser/unzip/imagick/include -I/home/myuser/unzip/imagick/main -I/home/myuser/unzip/imagick -I/usr/include/php/20210902 -I/usr/include/php/20210902/main -I/usr/include/php/20210902/TSRM -I/usr/include/php/20210902/Zend -I/usr/include/php/20210902/ext -I/usr/include/php/20210902/ext/date/lib -DHAVE_CONFIG_H -g -O2 -DZEND_COMPILE_DL_EXT=1 -c /home/myuser/unzip/imagick/imagick_file.c -MMD -MF imagick_file.dep -MT imagick_file.lo  -fPIC -DPIC -o .libs/imagick_file.o
In file included from /home/myuser/unzip/imagick/php_imagick_file.h:24,
                 from /home/myuser/unzip/imagick/imagick_file.c:22:
**/home/myuser/unzip/imagick/php_imagick_defs.h:25:12: fatal error**: MagickWand/MagickWand.h: No such file or directory
   25 | #  include <MagickWand/MagickWand.h>
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~
`

Curiously, the output from `configure` says 

`checking for MagickWand.h or magick-wand.h header... user location /usr/local/include/ImageMagick-7/MagickWand/MagickWand.h`

so it seems like it knows the right location, but `make` still can't find it.

I just noticed that, below the line quoted above, `configure` outputs these two no-so-encouraging messages:

`/usr/local/bin/MagickWand-config: 53: --libs: not found
/usr/local/bin/MagickWand-config: 41: --cflags: not found`

related?  I don't know.

Thanks very much for working through this with me!

**Comment by Danack** [comment] 2022-09-08 15:11
Can you confirm you ran `make install` when building ImageMagick?

If so can you post the whole contents of config.log the is generated after running the `configure` command?


> But I couldn't find another way to get that path included.... Advice on the proper way to do that would be greatly appreciated. 

If the appropriate tools are installed, you shouldn't need to do anything.

Every C (or C-like) library that gets installed with headers should be either setting up a "package config" info, of where to find the C headers and libraries, or because ImageMagick is ancient it has its own custom way of doing that also.

The most likely thing is it sounds like ImageMagick was compiled but not installed. But it's kind of confusing that you aren't getting a bigger error message saying what the error is.

**Comment by davidreedernst** [comment] 2022-09-08 15:57
I did indeed do a make install (as root). I scrolled back in my terminal to look for errors, I do have two warnings:

`libtool: warning: relinking 'MagickWand/libMagickWand-7.Q16HDRI.la'`

`libtool: warning: relinking 'Magick++/lib/libMagick++-7.Q16HDRI.la'`

Other than that, the ImageMagick `make install` run looks happy.  When I first tried to use it from the command line, I got "not found" errors, but after running `ldconfig /usr/local/lib` as root, it started working.  For instance:

```
$ convert -version
Version: ImageMagick 7.1.0-47 Q16-HDRI x86_64 20393 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5) 
Delegates (built-in): 
Compiler: gcc (9.4)
```
Here's the config.log from imagick make... there are errors in there, I'm feeling hopeful that those might clue you in as to what I've done wrong.  

[config.log](https://github.com/Imagick/imagick/files/9528465/config.log)

**Comment by Danack** [comment] 2022-09-08 19:13
Apparently there is a shortcut for closing issues which I hit by accident...

**Comment by davidreedernst** [comment] 2022-09-08 19:27
I think you're zeroing in on the problem here. The output from that config command is below, and it's clearly an error.  At first I thought that the script didn't understand the arguments, but no, it's actually just running something broken. Note the last case where I use an invalid argument and get the usage statement. 

```
$ /usr/local/bin/MagickWand-config --libs
/usr/local/bin/MagickWand-config: 53: --libs: not found
$ /usr/local/bin/MagickWand-config --cflags
/usr/local/bin/MagickWand-config: 41: --cflags: not found
$ /usr/local/bin/MagickWand-config --whatever
Usage: MagickWand-config [--cflags] [--cppflags] [--exec-prefix] [--ldflags] [--libs] [--prefix] [--version]
```

Looking at the code in the script, I see that it's trying to run "--cflags" as a command.  It seems like there should be something before the dashes, like "echo" maybe? There even seems to be an extra space before the dashes, as if there was something supposed to be there (like the code that generated it was something like `$COMMAND --cflags ...` but $COMMAND was the empty string so you just got a space and then the dashes...

```
    --version)
      echo '7.1.0-47 Q16 HDRI'
      ;;
    --cflags)
       --cflags MagickWand-7.Q16HDRI
      ;;
### lines omitted for breveity
    --libs)
       --libs MagickWand-7.Q16HDRI
      ;;
```

I think you're going to tell me that this file was output by the ImageMagick compilation process, and that there actually is a bug but it's with them instead of with imagick.  Is that right?  Any sense of what these lines should be?

**Comment by Danack** [comment] 2022-09-08 19:55
> It seems like there should be something before the dashes,

Yeah.

I've posted the full version of my `MagickWand-config` program below. That's just for info, not copying. But basically it should probably be running something like:

```
/usr/bin/pkg-config --cflags MagickWand-7.Q16HDRI
```

Can you:

* install pkg-config through apt/yum.
* rerun configure for ImageMagick.
* `make clean` && `make install` for ImageMagick, and see if /usr/local/bin/MagickWand-config gets updated to something that gives sensible output for `/usr/local/bin/MagickWand-config --cflags`


If it still doesn't look like it's generating an appropriate MagickWand-config program, please can you post the config.log of ImageMagick....but at that point I might need to pass you onto the ImageMagick people.




```
#!/bin/sh
#
# Configure options script for re-calling MagickWand compilation options
# required to use the MagickWand library.
#

prefix=/usr/local
exec_prefix=${prefix}

usage="\
Usage: MagickWand-config [--cflags] [--cppflags] [--exec-prefix] [--ldflags] [--libs] [--prefix] [--version]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      echo "Example: gcc \`MagickWand-config --cflags --cppflags\` -o wand wand.c \`MagickWand-config --ldflags --libs\`" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case "$1" in
    -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
    *) optarg= ;;
  esac
  case $1 in
    --prefix=*)
      prefix=$optarg
      ;;
    --prefix)
      echo $prefix
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo '7.1.0-13 Q16 HDRI'
      ;;
    --cflags)
      /usr/bin/pkg-config --cflags MagickWand-7.Q16HDRI
      ;;
    --cxxflags)
      /usr/bin/pkg-config --cflags MagickWand-7.Q16HDRI
      ;;
    --cppflags)
      /usr/bin/pkg-config --cflags MagickWand-7.Q16HDRI
      ;;
    --ldflags)
      /usr/bin/pkg-config --libs MagickWand-7.Q16HDRI
      ;;
    --libs)
      /usr/bin/pkg-config --libs MagickWand-7.Q16HDRI
      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done

```

**Comment by davidreedernst** [comment] 2022-09-08 21:38
Ok, serious progress. Rebuilding ImageMagick from scratch did result in `/usr/bin/pkg-config` being inserted in the `/usr/local/bin/MagickWand-config` file.  Not surprisingly, that got rid of the error that I was getting, and imagick `make` ran cleanly.  `make test` now skipped all tests (saying "test suite requires format png but not available"), but make install seemed happy. I think we're past the hurdle that I was stuck on. I'm still not seeing imagick in the output of `php -m`, but I'm guessing that that's some mundane configuration issue at this point.  

I guess the question is: why didn't it work the first time?  I wonder if I didn't have the pkg-config package installed before. It was installed just now -- that is, you asked me to install it, but when I tried, it said it was already installed with the latest version.  However, it's possible that it wasn't installed before my first attempt to build imagemagick, and somewhere in between it got installed as a dependency of some other package I installed.  Honestly, I would have expected it to be part of the apt `build-essential` package, which I definitely installed before building imagemagick... so, my theory isn't great. But, maybe something along those lines.

Anyway, thank you very much. You've been extremely helpful, and whatever caused the issue, it seems very clear that it wasn't even related to the package you maintain. If you happen to have a hint as to why `php -m` doesn't show imagick, I'd love to hear it, but you've gone far beyond the call of duty already, I can just try to troubleshoot that myself.

**Comment by Danack** [comment] 2022-09-08 23:20
> "test suite requires format png but not available"

For that, apt install libpng, and then reconfigure and recompile ImageMagick, and then Imagick.

> I guess the question is: why didn't it work the first time?

Who knows...there's not much point investigating why stuff failed to work in the past.

But you might at some point want to investigate using docker, vagrant or something similar for doing development work in. That allows you to have a reproducible environment, which takes some of the surprise away....

> If you happen to have a hint as to why php -m doesn't show imagick,

The tests setup their own ini settings. You have to manually add `extension=imagick.so` to the php ini file use by PHP on the command line in general. The location of that file can be found with `php --ini`

> Anyway, thank you very much. You've been extremely helpful, and whatever caused the issue,

No worries. Probably just balances out some of the trolling I do elsewhere...

**Comment by Danack** [comment] 2022-09-14 15:39
anyway, closing this as there's nothing for me to fix.

**Closed by Danack** 2022-09-14 15:39 UTC
