### ISSUE TITLE
Issue with Tiff image resizing

### ISSUE THREAD

**Issue by ContactPointIT** [Imagick/imagick#447] opened 2021-07-08 04:33 UTC
Hi,

We are using ImageMagick plugin for one of our websites (https://shop.print2metal.com/) and we have encountered an issue when we upload a Tiff image with custom size on the website. In such instance, the image saved on the server is not of the requested size. 

The site requires the user to first upload an image, and the image is handled by imagick while upload and gets saved. Next, the user can specify the size they want for the image and Save. At this point, when we provide a custom size such as 22 x 17.5 inch, the resized image should get saved, but the saved image is not of the requested size. 

This happens only with TIFF images and not with Jpegs. Can you please assist with this?

Following is the code used to do the initial upload. I have provided the values that result out of uploading a tiff image of original size 8433 x 4743.

 ```
//create the image object
    $image = new Imagick($imgPath);
    // resize the image to size of editor
    $image->resizeImage(8433, 0, imagick::FILTER_UNDEFINED, 1, 0);
    //crop image to viewport dimensions
    $image->cropImage(0,0,0,0);
    //reset image
    $image->resetImagePage("0x0+0+0");

    //save the image
    $output_filename = $root."/uploaded_images/savedimages/".$image_name.".".formatFormat($image->getImageFormat());
 
    $image->writeImage($output_filename);
} catch (Exception $e) {
    echo 'Caught exception: ',  $e->getMessage(), "n";
}

//make the web friendly version
$web_friendly = new ImagickThumbnail($output_filename);
$web_friendly->thumbnailImage(300, 0, false);
$web_friendly->setImageFormat('jpg');
$web_friendly_name = $root."/uploaded_images/savedimages/wf_".$image_name.".jpg";

$web_friendly->writeImage($web_friendly_name);


function formatFormat($format)
{
    $format = strtolower($format);
    if ($format == "jpeg") {
        $format = "jpg";
    }
    return $format;
}

```

After providing the custom size and save, the image handling does the following code:
```
try
{
    $image = new Imagick();
    $image->setResourceLimit( Imagick::RESOURCETYPE_MEMORY, 33554432  );

    $image->setOption('jpeg:size', 8433.'x'.4750.59);
    $image->readImage($imgPath);

	$image->resizeImage(8433, 4750.59, imagick::FILTER_UNDEFINED, 1, 0);
	//crop image to viewport dimensions
	$image->cropImage(3682.41, 4750.59, 0, 0);
	//reset image
	$image->resetImagePage("3682.41x4750.59+0+0");
	    
    //save the image
    $output_filename = $root."/uploaded_images/savedimages/".$image_name.".".formatFormat($image->getImageFormat());
    
    $image->writeImage($output_filename);
} catch (Exception $e) {
    echo 'Caught exception: ',  $e->getMessage(), "n";
}

function formatFormat($format)
{
    $format = strtolower($format);
    if ($format == "jpeg") {
        $format = "jpg";
    }
    return $format;
}
````

Thanks in advance.

**Comment by Danack** [comment] 2021-07-08 09:52
When reporting issues please submit a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/).

The code provided doesn't run. Not only does it give an error on `undefined variable $imgPath` but the line:

```
$image->setOption('jpeg:size', 8433.'x'.4750.59);
```
Doesn't compile 


btw, you can't crop or set image sizes to floating point numbers e.g. is bogus `$image->cropImage(3682.41, 4750.59, 0, 0);`


I spent a few minutes trying to figure out what your code was trying to do, and made this runnable code:

```
// Generate a tiff
$blank = new Imagick();
$blank->newPseudoImage(8433, 4743, "magick:logo");
$blank->setFormat("tiff");
$blank->writeImage(__DIR__ . "/test_input.tiff");


// Do some stuff
$image = new Imagick();
$image->setResourceLimit(Imagick::RESOURCETYPE_MEMORY, 33554432);

$image->setOption('jpeg:size', 8433 . 'x' . 4750);
$image->readImage(__DIR__ . "/test_input.tiff");

$image->resizeImage(8433, 4750, imagick::FILTER_UNDEFINED, 1, false);
//crop image to viewport dimensions
$image->cropImage(3682, 4750, 0, 0);

//reset image
$image->resetImagePage("3682x4750.59+0+0");
$output_filename = __DIR__ . "/output.jpg";
$image->writeImage($output_filename);

// Reopen image
$reopened_image = new Imagick(__DIR__ . "/output.jpg");
echo "22 / 17.5 ratio is: " . (22 / 17.5) . "\n";
echo "Crop ratio of 4750 x 3682 " . (4750 / 3682) . "\n";
echo "Actual ratio is: " . ($reopened_image->getImageHeight() / $reopened_image->getImageWidth()) . "\n";
```

Which gives the output of:

> 22 / 17.5 ratio is: 1.2571428571429
> Crop ratio of 4750 x 3682 1.2900597501358
> Actual ratio is: 1.2900597501358

Your code appears to be cropping the image to a particular size, which doesn't match the ratio of 22 x 17.5 which you said you wanted.

Please can you update the reproduce case I posted to more accurately show the error, and say a bit more clearly which bit you think is going wrong.

If you think the reproduce case with the image being generated through Imagick::newPseudoImage doesn't show the problem, you may need to provide a tiff image that does show the problem. You may need to put it into a zip file as github doesn't allow tiff uploads. Or put it on a website somewhere for download.

**Comment by ContactPointIT** [comment] 2021-07-14 23:54
Sorry about the $imgPath variable and thanks for the reproduce code.

But I am unsure as to where the issue is occurring within the reproduce code as well. From what you have mentioned, the values for cropImage seems to not match the size required! So I have uploaded the particular .tiff file that surely does cause this issue, as asked. Can you please help seeing if the same occurs with this image, as it does with the test_input.tiff that you are using?

Thank you!

**Comment by ContactPointIT** [comment] 2021-07-15 01:09
Thanks for trying by reproducing the code on your side, and sorry about the $imgPath variable.

From what you have tried, the cropImage values seem to be producing a different size. But I am still unable to point out what is the issue. So I have provided the tiff image that is actually causing the problem, as you asked. Can you please try your code with this image and help me figure out what is the issue?

The image is accessible from the below link.

Thanks!

https://contactpointonline.sharepoint.com/:f:/g/Ei3qy7Pm3dFHm-L7WjLtDm8BDa_WBIFQdCQH5Pt8ATcIDQ?e=E1TG2n

**Comment by Danack** [comment] 2021-07-15 15:39
That image is not available to me.

<img width="640" alt="Screen Shot 2021-07-15 at 16 37 22" src="https://user-images.githubusercontent.com/1505719/125816179-eca3251c-63b6-4e35-b15d-733b6cdd00b6.png">

I'm pretty sure if you put it in a zip file, you can upload it here. or email it to me. Email is on https://github.com/Danack

**Comment by ContactPointIT** [comment] 2021-07-21 23:21
Thank you! Have emailed you the image.

**Comment by Danack** [comment] 2021-07-22 17:04
Okay, I have the image.

I still don't understand what problem you think I should be looking at. Running this code:

```
$image = new Imagick();
$image->readImage(__DIR__ . "/Sample_tiff_image.tiff");

$image->resizeImage(8433, 4750, imagick::FILTER_LANCZOS, 1, false);
//crop image to viewport dimensions
$image->cropImage(3682, 4750, 0, 0);

//reset image
$image->resetImagePage("3682x4750.59+0+0");
$output_filename = __DIR__ . "/output.jpg";
$image->writeImage($output_filename);

// Reopen image
$reopened_image = new Imagick(__DIR__ . "/output.jpg");
echo "22 / 17.5 ratio is: " . (22 / 17.5) . "\n";
echo "Crop ratio of 4750 x 3682: " . (4750 / 3682) . "\n";
echo "Actual ratio is: " . ($reopened_image->getImageHeight() / $reopened_image->getImageWidth()) . "\n";
```

which is my best understanding of what your code is doing, the output is:

```
22 / 17.5 ratio is: 1.2571428571429
Crop ratio of 4750 x 3682: 1.2900597501358
Actual ratio is: 1.2900597501358
```

i.e. the cropping is doing what it is told to do, but the ratio of 22 / 17.5  is not the same as 4750 / 3682.

Please can you modify that code, so that it shows the behaviour that you think is going wrong, i.e. it is a [Short, Self Contained, Correct (Compilable), Example](http://sscce.org/) and a description of what you think is wrong.

**Comment by ContactPointIT** [comment] 2021-07-28 00:24
I have modified the code by correcting the values passed for cropping the image.

```
$image = new Imagick();
$image->readImage(__DIR__ . "/Sample_tiff_image.tiff");

$image->resizeImage(8433, 4750, imagick::FILTER_LANCZOS, 1, false);
//crop image to viewport dimensions
$image->cropImage(6156, 4750, 0, 0);

//reset image
$image->resetImagePage("6156.09x4750.59+0+0");
$output_filename = __DIR__ . "/output.jpg";
$image->writeImage($output_filename);

// Reopen image
$reopened_image = new Imagick(__DIR__ . "/output.jpg");
echo "22 / 17.5 ratio is: " . (22 / 17.5) . "\n";
echo "Crop ratio of 6156 x 4750: " . (6156 / 4750) . "\n";
echo "Actual ratio is: " . ($reopened_image->getImageHeight() / $reopened_image->getImageWidth()) . "\n";
```
Hopefully this clears it out. Thanks.

**Comment by Danack** [comment] 2021-08-02 19:13
You're using values of 6156 width and 4750 height. And then calculating the ratio as width/height. But for this line of code:

```
echo "Actual ratio is: " . ($reopened_image->getImageHeight() / $reopened_image->getImageWidth()) . "\n";
```

You've switched to height/width. Switching it back round gives:

> 22 / 17.5 ratio is: 1.2571428571429
> Crop ratio of 6156 x 4750: 1.296
> Actual ratio is: 1.296

i.e. the code appears to be doing exactly what you are telling it to do.

It's been over a month since your team [opened an issue](https://github.com/Imagick/imagick/issues/440#issue-925719486). Even now I still have no idea what bug you are trying to report.

Please can you clearly state exactly what you think is going wrong, otherwise I'm just going to assume that it's a bug elsewhere that's no the responsibility of Imagick to fix.

**Comment by Danack** [comment] 2021-08-15 19:53
Going to close this as I can't see a problem in Imagick to investigate.

**Closed** 2021-08-15 19:56 UTC
