### ISSUE TITLE
Can't install/build on osx

### ISSUE THREAD

**Issue by fridzema** [Imagick/imagick#430] opened 2021-06-16 13:30 UTC
```
osx 11.4
php  8.0.7 
imagemagick 7.1.0-0
```

Can't install pecl extension and/or build from source. 
I was building the extension from source since php8 with no problems until today. 

@yyongpil has posted an answer that worked for someone, don't really understand why and what to do?
`libomp` is already present on my system (tried rebuilding).
Where can i find the m4 config file?
Is there any reason we have to configure this manually?

Installing or building from returns the following error:
```
ld: library not found for -lgomp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [imagick.la] Error 1
```

Related:
https://github.com/Imagick/imagick/issues/358
https://github.com/Imagick/imagick/issues/358#issuecomment-859475795
https://github.com/Imagick/imagick/issues/358#issuecomment-862365343

**Comment by Xusually** [comment] 2021-06-16 13:48
The file "config.m4" is at the root directory of imagick's source code.

try:
wget https://pecl.php.net/get/imagick-3.5.0RC2.tgz
tar xvf imagick-3.5.0RC2.tgz
cd imagick-3.5.0RC2
-----
then find and modify the config.m4 file as @yyongpil mentioned:
find these two lines:
PHP_CHECK_FUNC(omp_pause_resource_all, gomp)
PHP_ADD_LIBRARY(gomp,, IMAGICK_SHARED_LIBADD)
replace them to:
PHP_CHECK_FUNC(omp_pause_resource_all, omp)
PHP_ADD_LIBRARY(omp,, IMAGICK_SHARED_LIBADD)
-----
phpize
./configure
make
make install

Works for me. Good luck.

**Comment by Danack** [comment] 2021-06-16 13:49
> Where can i find the m4 config file?

https://github.com/Imagick/imagick/blob/master/config.m4 and https://github.com/Imagick/imagick/blob/master/imagemagick.m4

> Is there any reason we have to configure this manually?

The configure command configures the build for your system. This creates a custom set of compile options depending on what the configure command finds on your system.

One example is whether to compile in [Imagick::setImagePixelColor](https://github.com/Imagick/imagick/blob/66264f4ef1e9deb63aac0da7356de62156fe2b73/php_imagemagick_version_defs.h#L32-L34) if you have an ImageMagick version later than version 0x709.

But I don't know what the issue is. It might make it easier for someone to help you if you post the full compile steps you're doing....

**Comment by Danack** [comment] 2021-06-16 14:04
@Xusually so it's just the file name that's the problem?

Can you do me favour and have a search through all the m4 files you might have on your machine for the word "gomp" and see if any of them have anything that looks like a check for whether "gomp" or "omp" should be used.

It sounds like something someone else will have already written the appropriate m4 invocation for...

**Comment by cspshadx** [comment] 2021-06-16 14:31
@Xusually works like a charm. thank u!

**Comment by yyongpil** [comment] 2021-06-16 14:58
@Danack It's just the macOS linker `ld` can't find `gomp`(GNU OpenMP) but `omp`(LLVM's OpenMP)

I'm not familiar with autoconf scripts/syntax but it seems like config.m4 is for UNIX and POSIX-conforming systems.
I think, if possible, adding some additional conditionals like below would solve the problem:

IF OPERATING SYSTEM IS `macOS(darwin)` USE `omp` (LLVM's OpenMP library)
```
PHP_CHECK_FUNC(omp_pause_resource_all, omp)
PHP_ADD_LIBRARY(omp,, IMAGICK_SHARED_LIBADD)
```

OTHERWISE USE `gomp` (GNU OpenMP library)
```
PHP_CHECK_FUNC(omp_pause_resource_all, gomp)
PHP_ADD_LIBRARY(gomp,, IMAGICK_SHARED_LIBADD)
```

**Comment by Danack** [comment] 2021-06-16 15:23
> I'm not familiar with autoconf scripts/syntax

No one is...it's the most widely used least understood technology.

Please can you search through the the m4 files you might have on your machine for the word "gomp" and see if any of them have any logic that looks like as you described?

**Comment by pnlinh-it** [comment] 2021-06-20 16:00
@yyongpil
Thank you. Work like a charm. 
I need to download source and config again because I run `phpize && ./configure && make` before change `gomp` to `omp`.

**Comment by Danack** [comment] 2021-06-23 17:48
The fix was merged. I don't have a mac build environment setup so can't test it, so if anyone can confirm it's worked after merging that would be great.

**Comment by yyongpil** [comment] 2021-06-24 09:15
Thanks @Danack 
I can confirm that it works after merging on macOS 10.15.7 with PHP 8.0.7 + imagemagick 7.1.0-1

**Comment by Danack** [comment] 2021-06-24 13:15
cool. thanks for confirmation.

**Closed by Danack** 2021-06-24 13:15 UTC

**Comment by pgrenaud** [comment] 2021-07-05 16:48
@Danack Wait, I'm confused. Was this fix released or not? Because I'm having this exact issue when trying to install imagick 3.5.0 on macOS with either PHP 7.3, 7.4 and 8.0.

**Comment by Danack** [comment] 2021-07-06 02:39
I still live in linear time, so no, the release on the 17th of June doesn't contain a fix merged on the 23rd.

I've been holding of doing an updated release as it just smelt wrong and didn't feel like that fix was right. 

I think I've just figured out what is nagging me, and the better way to address the issue: #445
