### ISSUE TITLE
FTBFS: php_imagick_read_image_using_imagemagick: tsrm_ls is undeclared

### ISSUE THREAD

**Issue by Whissi** [Imagick/imagick#264] opened 2019-01-14 14:15 UTC
Current git master is failing with
```
libtool: compile:  x86_64-pc-linux-gnu-gcc -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -DMAGICKCORE_HDRI_ENABLE=1 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/include/ImageMagick-7 -I. -I/var/tmp/portage/dev-php/pecl-imagick-3.4.3_p20181129/work/php5.6 -DPHP_ATOM_INC -I/var/tmp/portage/dev-php/pecl-imagick-3.4.3_p20181129/work/php5.6/include -I/var/tmp/portage/dev-php/pecl-imagick-3.4.3_p20181129/work/php5.6/main -I/var/tmp/portage/dev-php/pecl-imagick-3.4.3_p20181129/work/php5.6 -I/usr/lib64/php5.6/include/php -I/usr/lib64/php5.6/include/php/main -I/usr/lib64/php5.6/include/php/TSRM -I/usr/lib64/php5.6/include/php/Zend -I/usr/lib64/php5.6/include/php/ext -I/usr/lib64/php5.6/include/php/ext/date/lib -I/usr/include/ImageMagick-7 -DHAVE_CONFIG_H -O2 -Og -pipe -march=ivybridge -mtune=ivybridge -mno-xsaveopt -Wno-error=unused-function -Wno-error=sign-compare -Wno-error=maybe-uninitialized -frecord-gcc-switches -c /var/tmp/portage/dev-php/pecl-imagick-3.4.3_p20181129/work/php5.6/imagick_file.c  -fPIC -DPIC -o .libs/imagick_file.o
/var/tmp/portage/dev-php/pecl-imagick-3.4.3_p20181129/work/php5.6/imagick_file.c: In function ‘php_imagick_read_image_using_imagemagick’:
/var/tmp/portage/dev-php/pecl-imagick-3.4.3_p20181129/work/php5.6/imagick_file.c:166:8: error: ‘tsrm_ls’ undeclared (first use in this function)
  (void)tsrm_ls;
        ^~~~~~~
/var/tmp/portage/dev-php/pecl-imagick-3.4.3_p20181129/work/php5.6/imagick_file.c:166:8: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:181: imagick_file.lo] Error 1
```

**Comment by Danack** [comment] 2019-03-28 12:31
Hmm. I can't reproduce this issue. 

Compiling against 5.6 works fine for me both for non-ZTS and ZTS.

Compiling against PHP master isn't supported yet as that has some changes required in extensions, but I'm not going to start those until closer to 8 release.

Feel free to re-open if you can provide complete working repro preferably in docker.

**Comment by tjhart** [comment] 2019-04-15 20:27
@Danack I can reproduce it. I just ran across it today. We've been using `laradock.io`. This particular commit: https://github.com/laradock/laradock/tree/v7.14

There are multiple containers. we're using php-fpm against PHP 5.6. Relevant configuration (`.env`) looks like this:

```
PHP_VERSION=5.6
# ...
PHP_FPM_INSTALL_IMAGEMAGICK=true

```

You should be able to modify `docker-compose.yml` and/or execute docker-compose to *just* build the php-fpm container and see the issue.

Note that this behavior has *changed* for me. I'm assuming the repositories it pulls against have updated versions. I've not changed anything relevant in my docker files or config.

**Comment by tjhart** [comment] 2019-04-15 21:19
@Danack and anyone else who finds this issue via a web search, I was able to get around this issue by updating my local copy of `https://github.com/laradock/laradock/blob/v7.14/php-fpm/Dockerfile`.

[Line 517](https://github.com/laradock/laradock/blob/v7.14/php-fpm/Dockerfile#L517) now reads:

```
    pecl install imagick-3.4.3
```

**Comment by Danack** [comment] 2019-04-15 22:02
So you're saying it's not an issue in imagick-3.4.3 - aka the current version?

Actually - I'm not sure what you're saying. If you think it's still an issue, please give me steps to reproduce the problem, as just pointing me to another repo is not a clear set of instructions.

**Comment by tjhart** [comment] 2019-04-15 23:10
@Danack 

I also encountered this issue. In my environment it occurs with a recent release candidate. I came across this issue while googling the exact error listed above. I was simply responding to your comment that you couldn't reproduce it, to be helpful. The comment is, as you requested, a `complete working repro preferably in docker.`

The description below isn't the smallest source needed. It's simply the easiest way I can contribute to helping. In my build today, the error occurred with `3.4.4-RC1`

To Reproduce
1. Be sure `git` is installed
2. Be sure a current version of `docker` is installed
3. Be sure your cache of docker containers and images do not contain a container previously built from below.

```bash
~ $ cd /tmp
/tmp $  git clone https://github.com/laradock/laradock
/tmp $ cd laradock
/tmp/laradock $ git checkout v7.14 #output omitted
/tmp/laradock $ cp env-example .env
/tmp/laradock$ # ... edit .env and set PHP_VERSION=5.6 will speed up the effort
/tmp/laradock $docker-compose up php-fpm

```
Build works fine if PHP_VERSION is set to 7.2

I know php 5.6 isn't supported. I do *not* know how that is related to the failure. I will gain nothing from this post. I was simply able to reproduce the problem, and thought I'd try to help. Do with it what you will.

**Comment by goodjack** [comment] 2019-04-16 07:00
Same issue here.

Laradock's php-fpm dockerfile:
https://github.com/laradock/laradock/blob/329462a637af77f466c2fd041c3d9a80d4ddd30c/php-fpm/Dockerfile#L515-L519

The command is `pecl install imagick`, and the current stable version of the imagick is `3.4.4RC1`.
![image](https://user-images.githubusercontent.com/1116129/56188192-6ab24500-6057-11e9-8fd2-d22169691633.png)

**Comment by Danack** [comment] 2019-04-16 10:29
Remi authored a fix for this. I'll retag a new version once he's confirmed another problem is also fixed.

**Comment by leymannx** [comment] 2019-04-16 11:18
Same for me on PHP 5.6.

Upgrading to PHP 7.2 fixed it. Was overdue anyway.

**Comment by Danack** [comment] 2019-05-30 11:32
This was fixed in the release.

**Closed by Danack** 2019-05-30 11:32 UTC
