### ISSUE TITLE
Cannot open EPS files uploaded via HTML form

### ISSUE THREAD

**Issue by msrumon** [Imagick/imagick#364] opened 2020-11-26 17:25 UTC
I can directly open `.jpg`, `.png` images uploaded via HTML form, even if it's inside temp directory (w/ `.tmp` extension). But I cannot open `.eps` files in the same way. Is there any limitation behind this behavior? Or it's merely a bug?

Below is the minimal code to reproduce the issue:

```php
<?php

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $tmpPath = $_FILES['image']['tmp_name'];
    if (is_uploaded_file($tmpPath)) {
        try {
            $image = new Imagick($tmpPath);
            echo 'Image uploaded! Properties:' . PHP_EOL;
            var_dump($image->getImageProperties());
            echo PHP_EOL;
        } catch (ImagickException $ex) {
            echo 'Thrown Exception:' . PHP_EOL;
            var_dump($ex);
            echo PHP_EOL;
        }
    }
}

?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <form action="" method="post" enctype="multipart/form-data">
        <label for="img">Choose an image:</label>
        <input type="file" name="image" id="img">
        <button>Upload</button>
    </form>
</body>

</html>
```

If you want to use a boiler plate, here's the repo link: https://github.com/msrumon/imagine-imagick-issue.

**Comment by Danack** [comment] 2020-11-26 22:39
Please try just opening a file that you know is a valid EPS file directly in index.php, rather than going through the upload. And just run it from the command line rather than going through a webserver.

And for your development server, you should get it setup so that it displays/logs errors. Please see: https://stackoverflow.com/questions/845021/how-can-i-get-useful-error-messages-in-php

**Comment by Danack** [comment] 2020-11-26 22:49
Oh, wait. The title of the bug should probably be "Cannot open EPS files that are tmp files with .tmp extension." 

Anyway, still. Please get the actual error.

**Comment by msrumon** [comment] 2020-11-27 04:06
Actual error message is: `Unable to open file /tmp/{some-random-string}.tmp`. You can also see the error by yourself as well if you run the snippet I provided, or the repo I've linked. It's not that much of code after all. And I can directly open EPS files, it's just the uploaded files I'm having problem with. If this is intended, I will find another solution. Otherwise, consider this as a bug. Thanks 😊

**Comment by Danack** [comment] 2020-11-27 11:52
> You can also see the error by yourself as well if you run the snippet I provided,

That snippet requires having a server setup with file uploading available. It's not trivial for me to reproduce your problem.

I'm also not particularly interested in going through a webserver as it's better to isolate "things that might be something I need to fix" from "things that are not working due to your webserver being misconfigured".

This:

> Actual error message is: Unable to open file /tmp/{some-random-string}.tmp

Doesn't actually sound like an Imagick error message. I have no idea where that error message is coming from.

Imagick errors look more like:

> Fatal error: Uncaught ImagickException: no decode delegate for this image format `PHP' @ error/constitute.c/ReadImage/562 in /var/app/bugReports/364/364.php:6

As I said, running just starting with a known good eps file, and opening it directly with code from the command line would be the place to start. Then after that i) move it to the tmp dir ii) change the filename to look like an uploaded file name iii) change the file permissions to be the same as they would be for a user uploaded file (all of owner, group and read/write/execute permissions.)

**Comment by msrumon** [comment] 2020-11-27 12:39
> That snippet requires having a server setup with file uploading available.

Seriously? If you have PHP installed on your machine, you could've just run `php -S localhost:4000` inside the folder where that snippet lives, and open that link to a browser. It's as simple as that! Anyway, moving on...

> Doesn't actually sound like an Imagick error message. I have no idea where that error message is coming from.

I get that error when I use the library w/ my Symfony 5 application. Okay, let's put that aside and focus on the issue w/ Imagick.

I ran the snippet I attached above, and found the following exception being thrown:

```bash
PHP Fatal error:  Uncaught ImagickException: PostscriptDelegateFailed `The system cannot find the file specified.
' @ error/ps.c/ReadPSImage/959
```

I get this for both uploading an EPS file and using an EPS file from file system. I have used [this file](https://people.sc.fsu.edu/~jburkardt/data/eps/circle.eps) for producing the error. Check [this video](https://www.dropbox.com/s/w0h2dcz6qdu9gtr/Imagick-imagick-364.mp4) for more info. Any idea about why this is happening? Thanks 😉

**Comment by Danack** [comment] 2020-11-27 12:54
> Seriously? If you have PHP installed on your machine, you could've just run php -S localhost:4000 

Some advice from an older programmer, to a younger programmer - [no feigning surprise](https://www.recurse.com/social-rules).

> Feigned surprise is when you act surprised when someone doesn’t know something. Responding with surprise in this situation makes people feel bad for not knowing things and less likely to ask questions in the future, which makes it harder for them to learn.

In this particular case, you are calling me an idiot for not having the same environment as you. 

> For the record, ['just'](https://signalvnoise.com/posts/439-four-letter-words) is a four letter word. My problem with it is that it is not a productive conversational technique. In this case it assumes that something is going to be simple, which means that the person who knows why something might be difficult has to push back, before the conversation even begins.

You would have been better asking 'can you not run it on your host machine' and the answer is no, as I don't install imagick on my host machine.

Anyway, that's a file permissions issue. The program that ImageMagick uses to read EPS files is either not present, not executing, or can't open the EPS files......and apparently as you've now so gracefully done the first thing I said you needed to do, you can apparently see that it's a general problem with EPS files, not anything to do with file uploading.

This code works fine for me:
```
$image->readImage(__DIR__ . "/circle.eps");
$image->setImageFormat('png');
$image->writeImage("circles.png");
```
There is a test environment for PHP 7.2 in the docker compose in the root of this project. I suggest testing against that, and then figuring out what the difference between it and your system is that causes a problem.

But as this isn't reproducible for me, closing for now.

**Closed by Danack** 2020-11-27 12:54 UTC

**Comment by msrumon** [comment] 2020-11-27 13:01
Okay thanks for your suggestions. I will run more tests and see if I can figure it out by myself.
